### PR TITLE
fix!: Refactor the repository ruleset code

### LINKED ISSUE #3429: Repository ruleset event doesn't match schema
I'm looking at the code for the `Ruleset` & `RepositoryRuleset` types and both of them seem to be representing the same GH resource with slightly different implementations (`Conditions` & `Rules`). I can see that the `Ruleset` type use for the REST API is technically valid even though it represents the rules as an opaque `json.RawMessage` (this is what I'm looking to fix). But the `RepositoryRuleset` and specifically the `RepositoryRulesetRule` type doesn't match the schema for the [repository_ruleset event](https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=edited#repository_ruleset), which is based on the same schema as for the REST API.

@gmlewis do you have additional context that I don't have to explain why this actually works? If not I plan on refactoring all of this code back to a common pattern as it used elsewhere as well as removing the `json.RawMessage` fields which cause issues in consumers such as the GH TF provider.

### PR DESCRIPTION
**Pull request by stevehipwell**
This PR refactors the repository ruleset functionality to make is consistent, the following items are the big picture changes.

- Consistently refer to repository rulesets as such
- Use the same `RepositoryRuleset` type in both the REST API and events
- Don't return an opaque `json.RawMessage` field when the actual type is known
- Added `RepositoryRulesetRules` to represent the ruleset rules in a strongly typed way (this could be swapped to `[]RepositoryRulesetRule` with the type data still present behind an `any`)
- Added `BranchRules` to represent the rules for a branch in a strongly typed way (this could be swapped to `[]BranchRule` with the type data still present behind an `any`)
- Fixed event repository ruleset rules

BREAKING CHANGES: The following types have been renamed:

- `Ruleset` -> `RepositoryRuleset`
- `RulesetLink` -> `RepositoryRulesetLink`
- `RulesetLinks` -> `RepositoryRulesetLinks`
- `RulesetRefConditionParameters` -> `RepositoryRulesetRefConditionParameters`
- `RulesetRepositoryNamesConditionParameters` -> `RepositoryRulesetRepositoryNamesConditionParameters`
- `RulesetRepositoryIDsConditionParameters` -> `RepositoryRulesetRepositoryIDsConditionParameters`
- `RulesetRepositoryPropertyTargetParameters` -> `Repository`
- `RulesetRepositoryPropertyConditionParameters` -> `RepositoryRulesetRepositoryPropertyConditionParameters`
- `RulesetOrganizationNamesConditionParameters` -> `RepositoryRulesetOrganizationNamesConditionParameters`
- `RulesetOrganizationIDsConditionParameters` -> `RepositoryRulesetOrganizationIDsConditionParameters`
- `RulesetConditions` -> `RepositoryRulesetConditions`
- `RepositoryRulesetEditedChanges` -> `RepositoryRulesetChanges`
- `RepositoryRulesetEditedSource` -> `RepositoryRulesetChangeSource`
- `RepositoryRulesetEditedSources` -> `RepositoryRulesetChangeSources`
- `RepositoryRulesetEditedConditions` -> `RepositoryRulesetUpdatedConditions`
- `RepositoryRulesetUpdatedConditionsEdited` -> `RepositoryRulesetUpdatedCondition`
- `RepositoryRulesetEditedRules` -> `RepositoryRulesetChangedRules`
- `RepositoryRulesetUpdatedRules` -> `RepositoryRulesetUpdatedRules`
- `RepositoryRulesetEditedRuleChanges` -> `RepositoryRulesetChangedRule`

Fixes: #3429.

@gmlewis this PR adds the the breaking changes in #3417. The event changes have been tested with real world data. I'm happy to discuss any of the changes.

### CODE REVIEW

**Comment by gmlewis** [comment]
Thank you, @stevehipwell !
Please run `./script/generate.sh` and push the changes to this PR.

**Comment by stevehipwell** [comment]
@gmlewis sorry I thought I had run it, but I was making change while reviewing the PR diff so I guess I missed running it for one of the changes. Should be right now.

File: github/event_types.go [hunk 1]
```diff
@@ -1521,14 +1521,73 @@ type RepositoryImportEvent struct {
...
+// RepositoryRulesetChangeSources represents multiple source changes for the ruleset.
+type RepositoryRulesetChangeSources struct {
+	From []string `json:"from,omitempty"`
+}
+
+// RepositoryRulesetChangedConditions holds changes to conditions in a ruleset.
+type RepositoryRulesetChangedConditions struct {
+	Added   []RepositoryRulesetConditions        `json:"added,omitempty"`
+	Deleted []RepositoryRulesetConditions        `json:"deleted,omitempty"`
+	Updated []RepositoryRulesetUpdatedConditions `json:"updated,omitempty"`
```
[the remark this answers is not in the document]
Comment (stevehipwell) [reply github/event_types.go:1556]: Could you explain why arrays need to be of pointers? I'm not disagreeing, I'd just like to get my mental model clearer.

File: github/rules.go [hunk 2]
```diff
@@ -0,0 +1,1251 @@
...
+}
+
+// RepositoryRulesetRule represents a GitHub ruleset rule object.
+type RepositoryRulesetRule struct {
+	Type       RulesetRuleType `json:"type"`
+	Parameters any             `json:"parameters,omitempty"`
+}
+
+// RepositoryRulesetRules represents a GitHub ruleset rules object.
+type RepositoryRulesetRules struct {
```
[the remark this answers is not in the document]
Comment (stevehipwell) [reply github/rules.go:241]: Good spot, they don't need them due to the custom marshaling code. I'll add a comment.

File: github/rules.go [hunk 3]
```diff
@@ -0,0 +1,1251 @@
...
+	Parameters *json.RawMessage `json:"parameters,omitempty"`
+}
+
+// MarshalJSON is a custom JSON marshaller for RulesetRules.
+func (r *RepositoryRulesetRules) MarshalJSON() ([]byte, error) {
+	// If new rules are added to RulesetRules the capacity needs increasing
+	arr := make([]json.RawMessage, 0, 21)
+
+	if r.Creation != nil {
+		bytes, err := marshalRepositoryRulesetRule(RulesetRuleTypeCreation, nil)
```
[the remark this answers is not in the document]
Comment (stevehipwell) [reply github/rules.go:483]: This is the case for rule types that don't have parameters. I'll add a comment.

File: github/event_types.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (gmlewis) [reply github/event_types.go:1556]: https://github.com/google/go-github/issues/1429#issuecomment-585995454

File: github/rules.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (stevehipwell) [reply github/rules.go:483]: I've modified this to be a bit clearer and pass the values down and then ignore them there if they're zero.

**Comment by stevehipwell** [comment]
@gmlewis I've pushed the changes you requested, and remembered to not force push! 🥳

File: github/rules.go [hunk 4]
```diff
@@ -651,8 +654,10 @@ func (r *RepositoryRulesetRules) MarshalJSON() ([]byte, error) {
 }
 
 // marshalRepositoryRulesetRule is a helper function to marshal a ruleset rule.
-func marshalRepositoryRulesetRule(t RulesetRuleType, params any) ([]byte, error) {
-	if params == nil {
+func marshalRepositoryRulesetRule[T any](t RulesetRuleType, params T) ([]byte, error) {
+	paramsType := reflect.TypeFor[T]()
```
Comment (gmlewis) [inline github/rules.go:658]: We try to avoid using the `reflect` package in non-test functions in this repo, but I see here where it makes it much nicer for the end user, so let's roll with it and see if we get any feedback.

One way around it, though, might be to write another generator that runs when `./script/generate.sh` is called which will iterate over all the possibilities and then perform a switch with a type cast and call the appropriate code.

If you agree, then maybe you could add a `// TODO: Use generator here instead of reflection` and open up an issue for you or someone else to implement in the future.  If you disagree, I would love to hear why you would want to stick with reflection.

File: github/rules.go [hunk 5]
```diff
@@ -704,7 +709,7 @@ func (r *RepositoryRulesetRules) UnmarshalJSON(data []byte) error {
 			r.RequiredDeployments = &RequiredDeploymentsRuleParameters{}
 
 			if w.Parameters != nil {
-				err = json.Unmarshal(*w.Parameters, r.RequiredDeployments)
+				err = json.Unmarshal(w.Parameters, r.RequiredDeployments)
```
Comment (gmlewis) [inline github/rules.go:712]: Throughout this PR, could you please use the more idiomatic Go construct of `if err := ... ; err != nil {` instead of the two-line equivalent, for consistency with the rest of this repo?

**Review by gmlewis — CHANGES_REQUESTED** [review]
Thank you, @stevehipwell !
Just a few more minor concerns, please, if you don't mind.

File: github/rules.go [hunk 6]
```diff
@@ -0,0 +1,1251 @@
...
+type RuleWorkflow struct {
+	Path         string  `json:"path"`
+	Ref          *string `json:"ref,omitempty"`
+	RepositoryID *int64  `json:"repository_id,omitempty"`
+	Sha          *string `json:"sha,omitempty"`
+}
+
+// CodeScanningRuleParameters represents the code scanning rule parameters.
+type CodeScanningRuleParameters struct {
+	CodeScanningTools []RuleCodeScanningTool `json:"code_scanning_tools"`
```
[the remark this answers is not in the document]
Comment (gmlewis) [reply github/rules.go]: It looks like this comment has not yet been addressed.

[the remark this answers is not in the document]
Comment (gmlewis) [reply github/rules.go]: WHUPS!  My bad.  Ignore that please.

File: github/rules.go (hunk 4 above)
Comment (stevehipwell) [reply github/rules.go:658]: I don't specifically disagree, but given we're talking about JSON marshaling (I'll try and remember to leave out the second l) where reflection is already being used I'm not sure what the issue is? Do you have some specific concerns?

FYI I had a working version using generics but it only worked with the pointer having been dereferenced (`new(T)` as the nil check). But I didn't think it was as easy to understand as the reflection version.

Comment (gmlewis) [reply github/rules.go:658]: Oh sorry, I forgot to explain _why_.  We (in this repo, and I, in general) tend to avoid reflection for production code whenever possible due to the possibly-significant performance hit it may incur.

So it might be more appropriate to add two comments here:

```
// TODO: benchmark the code that uses reflection
// TODO: Use a generator here instead of reflection if there is a significant performance hit
```

File: github/rules.go [hunk 7]
```diff
@@ -238,6 +239,7 @@ type RepositoryRulesetRule struct {
 }
 
 // RepositoryRulesetRules represents a GitHub ruleset rules object.
+// This type doesn't have JSON annotations as it uses custom marshalling.
```
[the remark this answers is not in the document]
Comment (stevehipwell) [reply github/rules.go:242]: TIL it's _marshaling_ with 1 _l_ but _marshalled_ with 2.

File: github/rules.go (hunk 4 above)
Comment (stevehipwell) [reply github/rules.go:661]: Done

**Comment by stevehipwell** [comment]
@gmlewis is there a reason why we're not making the update functions (e.g. `UpdateRuleset`) do an actual update with all fields rather than supporting patching as the default behaviour? I know the APIs can function like this, but we don't have to use them that way. When I see `UpdateRuleset` I expect the ruleset to look like the payload after a successful apply. Then if patch functionality is required, we could add `PatchRuleset` as additional functionality.

File: github/rules.go (hunk 5 above)
Comment (stevehipwell) [reply github/rules.go]: Actually I can't see a single example of this pattern in the whole repo... 👀

File: github/rules.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (gmlewis) [reply github/rules.go]: Not according to Google, at least for American English:

American-English-2025-01-14_08-50-56

File: github/rules.go (hunk 5 above)
Comment (gmlewis) [reply github/rules.go]: You can't find `if err := ...; err != nil {` anywhere?
I see them:

```
$ rg 'if err :=' | wc -l
      65
```

**Comment by gmlewis** [comment]
> @gmlewis is there a reason why we're not making the update functions (e.g. `UpdateRuleset`) do an actual update with all fields rather than supporting patching as the default behaviour? I know the APIs can function like this, but we don't have to use them that way. When I see `UpdateRuleset` I expect the ruleset to look like the payload after a successful apply. Then if patch functionality is required, we could add `PatchRuleset` as additional functionality.

I'm betting that the original endpoint was poorly named and I didn't catch it.

Since this is a fairly significant breaking change, I would say that now is the time in this PR to make the method names actually describe what they are doing.

So feel free to make them consistent in your renaming.

File: github/rules.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (stevehipwell) [reply github/rules.go]: OK, I'm in the UK so that might explain _marshalled_ but the same dictionary was happy with _marshaling_. I'll update.

File: github/rules.go (hunk 5 above)
Comment (stevehipwell) [reply github/rules.go]: I might have been having a moment this morning, let's blame it on a lack of sleep... :disappointed:

File: github/rules.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (stevehipwell) [reply github/rules.go]: Done

File: github/rules.go (hunk 5 above)
Comment (stevehipwell) [reply github/rules.go]: Done

**Comment by gmlewis** [comment]
> Would this be better as a separate but linked PR? I expect to change the behaviour of the update functions and add patch functions. The standard struct would lose the `omitempty` annotations and a new `Patch*` struct would be introduced for the patch method with the `omitempty` annotations. We could then remove the custom functions to unset specific fields.

Absolutely, if you don't mind... that sounds great.  Thank you, @stevehipwell !

File: github/rules.go [hunk 8]
```diff
@@ -0,0 +1,1208 @@
+// Copyright 2025 The go-github AUTHORS. All rights reserved.
```
Comment (gmlewis) [inline github/rules.go:1]: Since everything in this file related to rulesets, do you want to rename this file from "rules.go" to "rulesets.go"?
(And its companion, "rules_test.go" to "rulesets_test.go"?)

Comment (stevehipwell) [reply github/rules.go:1]: I just realised I'd got the naming slightly wrong; `RepositoryRulesetRule` -> `RepositoryRule`. The _rules.go_ file contains the following types.

```mermaid
flowchart LR
    A[RepositoryRuleset] --> B[RepositoryRulesetRules] --> C[RepositoryRule]
    D[BranchRules] --> C
```

Comment (gmlewis) [reply github/rules.go:1]: Your mermaid diagram is really nice and yet so simple... Would GitHub display this diagram properly if it were included in a comment at the top of `rules.go` when viewing that file?
(Just curious - no action necessary.)

Comment (stevehipwell) [reply github/rules.go:1]: So thoughts on if we need any more changes to this PR?

Comment (gmlewis) [reply github/rules.go:1]: > I just realised I'd got the naming slightly wrong; `RepositoryRulesetRule` -> `RepositoryRule`. The _rules.go_ file contains the following types.

I was holding off until you addressed this, but if you are good to go, I'll review it.

**Review by gmlewis — APPROVED** [review]
Thank you, @stevehipwell and thanks also for your patience with my requests for changes... I really appreciate it!
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

File: github/rules.go (hunk 8 above)
Comment (stevehipwell) [reply github/rules.go:1]: Sorry I thought I'd pushed, I've pushed now.

**Review by gmlewis — APPROVED** [review]

**Comment by stevehipwell** [comment]
@gmlewis and suggestions for who to ask to give this a second review?

**Comment by gmlewis** [comment]
> @gmlewis and suggestions for who to ask to give this a second review?

I currently don't have any suggestions for volunteers and I try not to ping people unless it is really important.
Feel free to reach out to any Go devs you know to come do a code review for you so we can move this along.
We welcome contributions from anyone wanting to help out. Thanks.

File: example/verifyartifact/main.go [hunk 9]
```diff
@@ -109,7 +109,6 @@ func main() {
 		}
 
 		err := runVerification(sev, pb, b)
-
```
Comment (alexandear) [inline example/verifyartifact/main.go:112]: Could you please be so kind as to revert this unrelated change? It makes the review process more difficult.

You can use these commands:
```sh
git restore --source=master example/verifyartifact/main.go
git commit -a -m "Revert unrelated changes"
```

Thank you.

File: github/code_scanning.go [hunk 10]
```diff
@@ -391,7 +391,7 @@ func (s *CodeScanningService) UploadSarif(ctx context.Context, owner, repo strin
 		return nil, nil, err
 	}
 
-	// This will always return an error without unmarshalling the data
+	// This will always return an error without unmarshaling the data
```
Comment (alexandear) [inline github/code_scanning.go:394]: Please revert unrelated change. It's better to create a separate PR that fixes all `unmarshalling` words altogether.

**Review by alexandear — CHANGES_REQUESTED** [review]

File: github/enterprise_rules.go [hunk 11]
```diff
@@ -76,14 +76,14 @@ func (s *EnterpriseService) UpdateEnterpriseRuleset(ctx context.Context, enterpr
 	return rs, resp, nil
 }
 
-// UpdateEnterpriseRulesetClearBypassActor clears the ruleset bypass actors for a ruleset for the specified repository.
+// UpdateRepositoryRulesetClearBypassActor clears the bypass actors for a repository ruleset for the specified enterprise.
 //
 // This function is necessary as the UpdateEnterpriseRuleset function does not marshal ByPassActor if passed as an empty array.
```
Comment (alexandear) [inline github/enterprise_rules.go:81]: Perhaps we should change the comment after renaming:
```suggestion
// This function is necessary as the UpdateRepositoryRuleset function does not marshal ByPassActor if passed as an empty array.
```

File: github/code_scanning.go (hunk 10 above)
Comment (stevehipwell) [reply github/code_scanning.go:394]: This change was explicitly requested by @gmlewis.

File: example/verifyartifact/main.go (hunk 9 above)
Comment (stevehipwell) [reply example/verifyartifact/main.go]: Done

File: github/code_scanning.go (hunk 10 above)
Comment (stevehipwell) [reply github/code_scanning.go:394]: And AFAIK it does fix all of the related typos.

File: github/event_types_test.go [hunk 12]
```diff
@@ -9560,1789 +9563,68 @@ func TestReleaseEvent_Marshal(t *testing.T) {
...
...tive, Conditions: &RepositoryRulesetConditions{RefName: &RepositoryRulesetRefConditionParameters{Include: []string{"~ALL"}, Exclude: []string{}}}, Rules: &RepositoryRulesetRules{Creation: &EmptyRuleParameters{}, Update: &UpdateRuleParameters{}, Deletion: &EmptyRuleParameters{}, RequiredLinearHistory: &EmptyRuleParameters{}, PullRequest: &PullRequestRuleParameters{AllowedMergeMethods: []MergeMethod{MergeMethodSquash, MergeMethodRebase, MergeMethodMerge}, DismissStaleReviewsOnPush: false, RequireCodeOwnerReview: false, RequireLastPushApproval: false, RequiredApprovingReviewCount: 2, RequiredReviewThreadResolution: false}, CodeScanning: &CodeScanningRuleParameters{CodeScanningTools: []*RuleCodeScanningTool{{AlertsThreshold: CodeScanningAlertsThresholdErrors, SecurityAlertsThreshold: CodeScanningSecurityAlertsThresholdHighOrHigher, Tool: "CodeQL"}}}}, NodeID: Ptr("n"), CreatedAt: &Timestamp{referenceTime}, UpdatedAt: &Timestamp{referenceTime}, Links: &RepositoryRulesetLinks{Self: &RepositoryRulesetLink{HRef: Ptr("a")}, HTML: &RepositoryRulesetLink{HRef: Ptr("a")}}}, Repository: repository, Organization: organization, Enterprise: enterprise, Installation: installation, Sender: sender}},
```
Comment (alexandear) [inline github/event_types_test.go:9608]: This line contains 2668 characters, which may make it difficult to edit in the future as fields change. Could you please format the JSON as it is done in the other tests in this file?

**Review by alexandear — CHANGES_REQUESTED** [review]

File: github/event_types_test.go (hunk 12 above)
Comment (stevehipwell) [reply github/event_types_test.go:9608]: @alexandear I'm going to have to disagree with you on this. As the tests should be tightly coupled with the JSON string it makes the most sense to make the JSON format as clear and unambiguous as possible. Therefore the compact representation is the obvious choice. If you want to edit the JSON it's going to be much easier to do so by copying the string and working on it as actual JSON (`jq -c '.'` will then format the JSON to be pasted back).

Please note that this test doesn't use `testJSONMarshal` like the other tests; that helper function can (and does) mask incorrect JSON by depending on the very marshaling code that's under test to format the JSON string.

File: github/enterprise_rules.go (hunk 11 above)
Comment (stevehipwell) [reply github/enterprise_rules.go]: Good spot, fixed.

File: github/code_scanning.go (hunk 10 above)
Comment (alexandear) [reply github/code_scanning.go:394]: I created a PR to address this #3441
Would you mind a review?

File: github/rules_test.go [hunk 13]
```diff
@@ -0,0 +1,101 @@
...
...],"strict_required_status_checks_policy":true}},{"type":"non_fast_forward"},{"type":"commit_message_pattern","parameters":{"operator":"starts_with","pattern":"test"}},{"type":"commit_author_email_pattern","parameters":{"operator":"starts_with","pattern":"test"}},{"type":"committer_email_pattern","parameters":{"operator":"starts_with","pattern":"test"}},{"type":"branch_name_pattern","parameters":{"operator":"starts_with","pattern":"test"}},{"type":"tag_name_pattern","parameters":{"operator":"starts_with","pattern":"test"}},{"type":"file_path_restriction","parameters":{"restricted_file_paths":["test1","test2"]}},{"type":"max_file_path_length","parameters":{"max_file_path_length":512}},{"type":"file_extension_restriction","parameters":{"restricted_file_extensions":[".exe",".pkg"]}},{"type":"max_file_size","parameters":{"max_file_size":1024}},{"type":"workflows","parameters":{"workflows":[{"path":".github/workflows/test1.yaml"},{"path":".github/workflows/test2.yaml"}]}},{"type":"code_scanning","parameters":{"code_scanning_tools":[{"alerts_threshold":"all","security_alerts_threshold":"all","tool":"test"},{"alerts_threshold":"none","security_alerts_threshold":"none","tool":"test"}]}}]`},
```
Comment (alexandear) [inline github/rules_test.go:25]: I'm not sure it's a good idea to put everything into one line.

Compare your variant:

```go
		{"all_rules_with_all_params", &RepositoryRulesetRules{Creation: &EmptyRuleParameters{}, Update: &UpdateRuleParameters{UpdateAllowsFetchAndMerge: true}, Deletion: &EmptyRuleParameters{}, RequiredLinearHistory: &EmptyRuleParameters{}, MergeQueue: &MergeQueueRuleParameters{CheckResponseTimeoutMinutes: 5, GroupingStrategy: MergeGroupingStrategyAllGreen, MaxEntriesToBuild: 10, MaxEntriesToMerge: 20, MergeMethod: MergeMethodSquash, MinEntriesToMerge: 1, MinEntriesToMergeWaitMinutes: 15}, RequiredDeployments: &RequiredDeploymentsRuleParameters{RequiredDeploymentEnvironments: []string{"test1", "test2"}}, RequiredSignatures: &EmptyRuleParameters{}, PullRequest: &PullRequestRuleParameters{AllowedMergeMethods: []MergeMethod{MergeMethodSquash, MergeMethodRebase}, DismissStaleReviewsOnPush: true, RequireCodeOwnerReview: true, RequireLastPushApproval: true, RequiredApprovingReviewCount: 2, RequiredReviewThreadResolution: true}, RequiredStatusChecks: &RequiredStatusChecksRuleParameters{DoNotEnforceOnCreate: Ptr(true), RequiredStatusChecks: []*RuleStatusCheck{{Context: "test1", IntegrationID: Ptr(int64(1))}, {Context: "test2", IntegrationID: Ptr(int64(2))}}, StrictRequiredStatusChecksPolicy: true}, NonFastForward: &EmptyRuleParameters{}, CommitMessagePattern: &PatternRuleParameters{Name: Ptr("cmp"), Negate: Ptr(false), Operator: PatternRuleOperatorStartsWith, Pattern: "test"}, CommitAuthorEmailPattern: &PatternRuleParameters{Name: Ptr("caep"), Negate: Ptr(false), Operator: PatternRuleOperatorStartsWith, Pattern: "test"}, CommitterEmailPattern: &PatternRuleParameters{Name: Ptr("cep"), Negate: Ptr(false), Operator: PatternRuleOperatorStartsWith, Pattern: "test"}, BranchNamePattern: &PatternRuleParameters{Name: Ptr("bp"), Negate: Ptr(false), Operator: PatternRuleOperatorStartsWith, Pattern: "test"}, TagNamePattern: &PatternRuleParameters{Name: Ptr("tp"), Negate: Ptr(false), Operator: PatternRuleOperatorStartsWith, Pattern: "test"}, FilePathRestriction: &FilePathRestrictionRuleParameters{RestrictedFilePaths: []string{"test1", "test2"}}, MaxFilePathLength: &MaxFilePathLengthRuleParameters{MaxFilePathLength: 512}, FileExtensionRestriction: &FileExtensionRestrictionRuleParameters{RestrictedFileExtensions: []string{".exe", ".pkg"}}, MaxFileSize: &MaxFileSizeRuleParameters{MaxFileSize: 1024}, Workflows: &WorkflowsRuleParameters{DoNotEnforceOnCreate: Ptr(true), Workflows: []*RuleWorkflow{{Path: ".github/workflows/test1.yaml", Ref: Ptr("main"), RepositoryID: Ptr(int64(1)), SHA: Ptr("aaaa")}, {Path: ".github/workflows/test2.yaml", Ref: Ptr("main"), RepositoryID: Ptr(int64(2)), SHA: Ptr("bbbb")}}}, CodeScanning: &CodeScanningRuleParameters{CodeScanningTools: []*RuleCodeScanningTool{{AlertsThreshold: CodeScanningAlertsThresholdAll, SecurityAlertsThreshold: CodeScanningSecurityAlertsThresholdAll, Tool: "test"}, {AlertsThreshold: CodeScanningAlertsThresholdNone, SecurityAlertsThreshold: CodeScanningSecurityAlertsThresholdNone, Tool: "test"}}}}, `[{"type":"creation"},{"type":"update","parameters":{"update_allows_fetch_and_merge":true}},{"type":"deletion"},{"type":"required_linear_history"},{"type":"merge_queue","parameters":{"check_response_timeout_minutes":5,"grouping_strategy":"ALLGREEN","max_entries_to_build":10,"max_entries_to_merge":20,"merge_method":"squash","min_entries_to_merge":1,"min_entries_to_merge_wait_minutes":15}},{"type":"required_deployments","parameters":{"required_deployment_environments":["test1","test2"]}},{"type":"required_signatures"},{"type":"pull_request","parameters":{"allowed_merge_methods":["squash","rebase"],"dismiss_stale_reviews_on_push":true,"require_code_owner_review":true,"require_last_push_approval":true,"required_approving_review_count":2,"required_review_thread_resolution":true}},{"type":"required_status_checks","parameters":{"do_not_enforce_on_create":true,"required_status_checks":[{"context":"test1","integration_id":1},{"context":"test2","integration_id":2}],"strict_required_status_checks_policy":true}},{"type":"non_fast_forward"},{"type":"commit_message_pattern","parameters":{"name":"cmp","negate":false,"operator":"starts_with","pattern":"test"}},{"type":"commit_author_email_pattern","parameters":{"name":"caep","negate":false,"operator":"starts_with","pattern":"test"}},{"type":"committer_email_pattern","parameters":{"name":"cep","negate":false,"operator":"starts_with","pattern":"test"}},{"type":"branch_name_pattern","parameters":{"name":"bp","negate":false,"operator":"starts_with","pattern":"test"}},{"type":"tag_name_pattern","parameters":{"name":"tp","negate":false,"operator":"starts_with","pattern":"test"}},{"type":"file_path_restriction","parameters":{"restricted_file_paths":["test1","test2"]}},{"type":"max_file_path_length","parameters":{"max_file_path_length":512}},{"type":"file_extension_restriction","parameters":{"restricted_file_extensions":[".exe",".pkg"]}},{"type":"max_file_size","parameters":{"max_file_size":1024}},{"type":"workflows","parameters":{"do_not_enforce_on_create":true,"workflows":[{"path":".github/workflows/test1.yaml","ref":"main","repository_id":1,"sha":"aaaa"},{"path":".github/workflows/test2.yaml","ref":"main","repository_id":2,"sha":"bbbb"}]}},{"type":"code_scanning","parameters":{"code_scanning_tools":[{"alerts_threshold":"all","security_alerts_threshold":"all","tool":"test"},{"alerts_threshold":"none","security_alerts_threshold":"none","tool":"test"}]}}]`},
```

with mine:

```go
		{
			"all_rules_with_all_params",
			&RepositoryRulesetRules{
				Creation:              &EmptyRuleParameters{},
				Update:                &UpdateRuleParameters{UpdateAllowsFetchAndMerge: true},
				Deletion:              &EmptyRuleParameters{},
				RequiredLinearHistory: &EmptyRuleParameters{},
				MergeQueue: &MergeQueueRuleParameters{
					CheckResponseTimeoutMinutes:  5,
					GroupingStrategy:             MergeGroupingStrategyAllGreen,
					MaxEntriesToBuild:            10,
					MaxEntriesToMerge:            20,
					MergeMethod:                  MergeMethodSquash,
					MinEntriesToMerge:            1,
					MinEntriesToMergeWaitMinutes: 15,
				},
				RequiredDeployments: &RequiredDeploymentsRuleParameters{
					RequiredDeploymentEnvironments: []string{"test1", "test2"},
				},
				RequiredSignatures: &EmptyRuleParameters{},
				PullRequest: &PullRequestRuleParameters{
					AllowedMergeMethods: []MergeMethod{
						MergeMethodSquash,
						MergeMethodRebase,
					},
					DismissStaleReviewsOnPush:      true,
					RequireCodeOwnerReview:         true,
					RequireLastPushApproval:        true,
					RequiredApprovingReviewCount:   2,
					RequiredReviewThreadResolution: true,
				},
				RequiredStatusChecks: &RequiredStatusChecksRuleParameters{
					DoNotEnforceOnCreate: Ptr(true),
					RequiredStatusChecks: []*RuleStatusCheck{
						{Context: "test1", IntegrationID: Ptr(int64(1))},
						{Context: "test2", IntegrationID: Ptr(int64(2))},
					},
					StrictRequiredStatusChecksPolicy: true,
				},
				NonFastForward: &EmptyRuleParameters{},
				CommitMessagePattern: &PatternRuleParameters{
					Name:     Ptr("cmp"),
					Negate:   Ptr(false),
					Operator: PatternRuleOperatorStartsWith,
					Pattern:  "test",
				},
				CommitAuthorEmailPattern: &PatternRuleParameters{
					Name:     Ptr("caep"),
					Negate:   Ptr(false),
					Operator: PatternRuleOperatorStartsWith,
					Pattern:  "test",
				},
				CommitterEmailPattern: &PatternRuleParameters{
					Name:     Ptr("cep"),
					Negate:   Ptr(false),
					Operator: PatternRuleOperatorStartsWith,
					Pattern:  "test",
				},
				BranchNamePattern: &PatternRuleParameters{
					Name:     Ptr("bp"),
					Negate:   Ptr(false),
					Operator: PatternRuleOperatorStartsWith,
					Pattern:  "test",
				},
				TagNamePattern: &PatternRuleParameters{
					Name:     Ptr("tp"),
					Negate:   Ptr(false),
					Operator: PatternRuleOperatorStartsWith,
					Pattern:  "test",
				},
				FilePathRestriction: &FilePathRestrictionRuleParameters{
					RestrictedFilePaths: []string{"test1", "test2"},
				},
				MaxFilePathLength: &MaxFilePathLengthRuleParameters{MaxFilePathLength: 512},
				FileExtensionRestriction: &FileExtensionRestrictionRuleParameters{
					RestrictedFileExtensions: []string{".exe", ".pkg"},
				},
				MaxFileSize: &MaxFileSizeRuleParameters{MaxFileSize: 1024},
				Workflows: &WorkflowsRuleParameters{
					DoNotEnforceOnCreate: Ptr(true),
					Workflows: []*RuleWorkflow{
						{
							Path:         ".github/workflows/test1.yaml",
							Ref:          Ptr("main"),
							RepositoryID: Ptr(int64(1)),
							SHA:          Ptr("aaaa"),
						},
						{
							Path:         ".github/workflows/test2.yaml",
							Ref:          Ptr("main"),
							RepositoryID: Ptr(int64(2)),
							SHA:          Ptr("bbbb"),
						},
					},
				},
				CodeScanning: &CodeScanningRuleParameters{
					CodeScanningTools: []*RuleCodeScanningTool{
						{
							AlertsThreshold:         CodeScanningAlertsThresholdAll,
							SecurityAlertsThreshold: CodeScanningSecurityAlertsThresholdAll,
							Tool:                    "test",
						},
						{
							AlertsThreshold:         CodeScanningAlertsThresholdNone,
							SecurityAlertsThreshold: CodeScanningSecurityAlertsThresholdNone,
							Tool:                    "test",
						},
					},
				},
			},
			`[{"type":"creation"},{"type":"update","parameters":{"update_allows_fetch_and_merge":true}},{"type":"deletion"},{"type":"required_linear_history"},{"type":"merge_queue","parameters":{"check_response_timeout_minutes":5,"grouping_strategy":"ALLGREEN","max_entries_to_build":10,"max_entries_to_merge":20,"merge_method":"squash","min_entries_to_merge":1,"min_entries_to_merge_wait_minutes":15}},{"type":"required_deployments","parameters":{"required_deployment_environments":["test1","test2"]}},{"type":"required_signatures"},{"type":"pull_request","parameters":{"allowed_merge_methods":["squash","rebase"],"dismiss_stale_reviews_on_push":true,"require_code_owner_review":true,"require_last_push_approval":true,"required_approving_review_count":2,"required_review_thread_resolution":true}},{"type":"required_status_checks","parameters":{"do_not_enforce_on_create":true,"required_status_checks":[{"context":"test1","integration_id":1},{"context":"test2","integration_id":2}],"strict_required_status_checks_policy":true}},{"type":"non_fast_forward"},{"type":"commit_message_pattern","parameters":{"name":"cmp","negate":false,"operator":"starts_with","pattern":"test"}},{"type":"commit_author_email_pattern","parameters":{"name":"caep","negate":false,"operator":"starts_with","pattern":"test"}},{"type":"committer_email_pattern","parameters":{"name":"cep","negate":false,"operator":"starts_with","pattern":"test"}},{"type":"branch_name_pattern","parameters":{"name":"bp","negate":false,"operator":"starts_with","pattern":"test"}},{"type":"tag_name_pattern","parameters":{"name":"tp","negate":false,"operator":"starts_with","pattern":"test"}},{"type":"file_path_restriction","parameters":{"restricted_file_paths":["test1","test2"]}},{"type":"max_file_path_length","parameters":{"max_file_path_length":512}},{"type":"file_extension_restriction","parameters":{"restricted_file_extensions":[".exe",".pkg"]}},{"type":"max_file_size","parameters":{"max_file_size":1024}},{"type":"workflows","parameters":{"do_not_enforce_on_create":true,"workflows":[{"path":".github/workflows/test1.yaml","ref":"main","repository_id":1,"sha":"aaaa"},{"path":".github/workflows/test2.yaml","ref":"main","repository_id":2,"sha":"bbbb"}]}},{"type":"code_scanning","parameters":{"code_scanning_tools":[{"alerts_threshold":"all","security_alerts_threshold":"all","tool":"test"},{"alerts_threshold":"none","security_alerts_threshold":"none","tool":"test"}]}}]`,
		},
```

Comment (alexandear) [reply github/rules_test.go:25]: You can use [golines](https://github.com/segmentio/golines) to automatically format long lines.

Comment (stevehipwell) [reply github/rules_test.go:25]: For the objects I agree with you, I'll make these multi line.

**Review by gmlewis — APPROVED** [review]
Thank you, @stevehipwell!
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

**Comment by stevehipwell** [comment]
@gmlewis I've added another test to try and improve the code coverage numbers.

File: github/rules.go [hunk 14]
```diff
@@ -0,0 +1,1208 @@
...
+		return nil, err
+	}
+
+	return json.Marshal(repositoryRulesetRuleWrapper{Type: t, Parameters: json.RawMessage(bytes)})
+}
+
+// UnmarshalJSON is a custom JSON unmarshaler for RulesetRules.
+func (r *RepositoryRulesetRules) UnmarshalJSON(data []byte) error {
+	// If new rules are added to RulesetRules the capacity needs increasing
+	arr := make([]repositoryRulesetRuleWrapper, 0, 21)
```
[the remark this answers is not in the document]
Comment (stevehipwell) [reply github/rules.go:678]: I'm happy to rename `arr` to `wrappers`, and I will. However I can't see a benefit for removing the `make()`, call but I can see a number of downsides including both performance and clarity.

**Comment by stevehipwell** [comment]
@gmlewis what are your thoughts on the coverage here? The new untested lines are basically the error block for the JSON marshaling code and adding coverage for these would be very verbose but not impossible.

**Comment by gmlewis** [comment]
> @gmlewis what are your thoughts on the coverage here? The new untested lines are basically the error block for the JSON marshaling code and adding coverage for these would be very verbose but not impossible.

Exactly right - that part of the code is marshaling and unmarshaling the JSON so the coverage tests would need to attempt to provide input to the functions with either bad structs (challenging) or bad JSON (e.g. `{[`) which I don't think is terribly beneficial in the big scheme of things. So I'm perfectly happy to ignore the CodeCov results in this PR. Thanks for asking.

File: github/rules.go [hunk 15]
```diff
@@ -480,177 +480,177 @@ type repositoryRulesetRuleWrapper struct {
 // MarshalJSON is a custom JSON marshaler for RulesetRules.
 func (r *RepositoryRulesetRules) MarshalJSON() ([]byte, error) {
 	// If new rules are added to RulesetRules the capacity needs increasing
-	arr := make([]json.RawMessage, 0, 21)
+	rawRules := make([]json.RawMessage, 0, 21)
```
Comment (gmlewis) [inline github/rules.go:483]: Can you please add a comment here as to why `21` was chosen for the capacity, for the benefit of the maintainers?

If it is completely arbitrary, then please move it entirely, as that is not idiomatic Go.
The Go team has gone to extensive lengths with benchmarking to make the defaults very reasonable, and if you don't have a good reason for the capacity, then it is not only distracting, but makes the code harder to read and understand, which also violates idiomatic Go, as one of the whole points of Go's design is that it should be super-easy to read and understand.

Therefore, if it is arbitrary, it is idiomatic Go to always take advantage of the zero-value of a type when its initial value is not the focus of the code. Therefore, this would simply be:

```go
  var rawRules []json.RawMessage
```

Short, sweet, and does not distract the reader into thinking there is something special going on here.
In fact, the comment on 482 is also distracting and reader-time-consuming, in my opinion, if there is nothing special going on here.

However, once again, if the `21` _IS_ important (it is not obvious to me how it possibly could be), then change the comment on 482 to explain _why_ `21` is important. Otherwise, this is just a magic number:
https://en.wikipedia.org/wiki/Magic_number_(programming)

**Review by gmlewis — CHANGES_REQUESTED** [review]
Requesting change to remove magic number.

**Comment by gmlewis** [comment]
Thank you, @alexandear for your review!

File: github/rules.go (hunk 15 above)
Comment (stevehipwell) [reply github/rules.go:483]: I'll add a comment, but basically there will always be between 1 and 21 items in the slice due to the GitHub data model. My understanding was that if you had prior knowledge on the size of a Go array/slice that you should explicitly set it? If I'm incorrectly informed in this case I'll happily remove the `make()` call.

Comment (gmlewis) [reply github/rules.go:483]: OK, fine, then please change the comment. Thanks.

Comment (stevehipwell) [reply github/rules.go:484]: I've removed 2 of the 3 cases as they were incorrect and improved the comment for the case where I think it's worth setting the capacity.

**Comment by stevehipwell** [comment]
@gmlewis hopefully this is ready for final review now.

File: github/rules.go [hunk 16]
```diff
@@ -0,0 +1,1207 @@
...
+// branchRuleWrapper is a helper type to unmarshal a branch rule.
+type branchRuleWrapper struct {
+	Type RepositoryRuleType `json:"type"`
+	BranchRuleMetadata
+	Parameters json.RawMessage `json:"parameters,omitempty"`
+}
+
+// UnmarshalJSON is a custom JSON unmarshaler for BranchRules.
+func (r *BranchRules) UnmarshalJSON(data []byte) error {
+	var wrappers []branchRuleWrapper
```
Comment (gmlewis) [inline github/rules.go:839]:
```suggestion
	var wrappers []*branchRuleWrapper
```

File: github/rules.go [hunk 17]
```diff
@@ -0,0 +1,1207 @@
...
+	if err != nil {
+		return nil, err
+	}
+
+	return json.Marshal(repositoryRulesetRuleWrapper{Type: t, Parameters: json.RawMessage(bytes)})
+}
+
+// UnmarshalJSON is a custom JSON unmarshaler for RulesetRules.
+func (r *RepositoryRulesetRules) UnmarshalJSON(data []byte) error {
+	var wrappers []repositoryRulesetRuleWrapper
```
Comment (gmlewis) [inline github/rules.go:678]:
```suggestion
	var wrappers []*repositoryRulesetRuleWrapper
```

**Review by gmlewis — CHANGES_REQUESTED** [review]
Why aren't your wrappers all slices of pointers to structs?
Unless you have a good reason, they should be.

File: github/rules.go (hunk 16 above)
Comment (stevehipwell) [reply github/rules.go]: Fixed now.

File: github/rules.go (hunk 17 above)
Comment (stevehipwell) [reply github/rules.go]: Fixed now.

**Review by gmlewis — APPROVED** [review]
Thank you, @stevehipwell and @alexandear!
LGTM
Merging.
