### PR TITLE
Correctly handle API errors when downloading Release Assets

### LINKED ISSUE #343: DownloadReleaseAsset swallows API errors & returns io.ReadCloser of error payload
If the API request to download a release asset fails, no `error` is returned but the `io.ReadCloser` of the error JSON payload is:

```go
package main

import (
	"fmt"
	"io"
	"os"

	"github.com/google/go-github/github"
)

func main() {
	client := github.NewClient(nil)

	rc, url, err := client.Repositories.DownloadReleaseAsset("not-a", "real-repo", 0)
	if err != nil {
		fmt.Println("error:", err)
	}

	if rc != nil {
		fmt.Print("rc: ")
		io.Copy(os.Stdout, rc)
		fmt.Print("\n")
		rc.Close()
	}

	if url != "" {
		fmt.Println("url:", url)
	}
}
```

Would expect:

```
→ go run main.go
error: Not Found
```

But what is returned:

```
→ go run main.go
rc: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
```

### PR DESCRIPTION
**Pull request by rodaine**
If `RepositoriesService.DownloadReleaseAsset` encounters an error from the GitHub API (e.g., 404 Not Found), The error would not be returned by the method and instead the error payload would be delivered as the `io.ReadCloser`. This patch resolves this with `CheckResponse`.

Fixes #343

/cc @willnorris (thanks for the help!)

### CODE REVIEW

**Comment by gmlewis** [comment]
LGTM. @rodaine - thank you for fixing this... it looks like I missed this case.
@googlebot - did you do your thing?

**Comment by rodaine** [comment]
No sweat! 😅  If you're referring to the CLA, I think I got the ✅

**Comment by willnorris** [comment]
👍

**Comment by parkr** [comment]
@rodaine Did you check the actual return value of the example error or is that out of scope?

**Comment by rodaine** [comment]
@parkr in the test? Since I'm handing it off to CheckResponse, that's somewhat beyond the scope of the test. Being consistent with the rest of the methods that use [`CheckResponse`](https://github.com/google/go-github/blob/master/github/github.go#L460), I figured bubbling that up to the consumer and allowing them to take action on it is probably best. All 3XX responses _should_ be captured by the [`CheckRedirect`](https://github.com/google/go-github/blob/master/github/repos_releases.go#L240) callback on the `http.Client`, so what remains are actual errors.

File: github/repos_releases_test.go [hunk 1]
```diff
@@ -253,6 +253,32 @@ func TestRepositoriesService_DownloadReleaseAsset_Redirect(t *testing.T) {
...
+		t.Error("Repositories.DownloadReleaseAsset did not return an error")
+	}
+
+	if resp != nil {
+		resp.Close()
+		t.Error("Repositories.DownloadReleaseAsset returned stream, want nil")
+	}
+
+	if loc != "" {
+		t.Error(`Repositories.DownloadReleaseAsset returned "%s", want empty ""`, loc)
```
Comment (shurcooL) [inline github/repos_releases_test.go]: This should be `t.Errorf`, not `t.Error`.

@willnorris, will you take an improved `.travis.yml` that would run vet as part of CI? It would've caught this issue.

Comment (willnorris) [inline github/repos_releases_test.go]: Certainly

Comment (rodaine) [inline github/repos_releases_test.go]: My bad! Good catch.

Comment (shurcooL) [inline github/repos_releases_test.go]: I'll fix both with 1 PR (it's a good way to verify that the CI changes detect the issue; first commit will fail CI, the second will succeed). /cc @rodaine
