### PR TITLE
Fix Google App Engine support and provide working example

### LINKED ISSUE #578: Using go-github on Google App Engine with recent context changes - any interest?
After importing the recent context changes in #529 into Google, I became aware that it is a bit trickier now to use this same code base either within an App Engine project or outside of one.

I had to pull a few tricks with `// +build appengine` and `// +build !appengine` in a couple new files and patched a couple other files to make it all work.

I'm not sure if anyone is really interested in these changes, but if you are, please let me know and I'll see if I can replicate the needed changes in a new PR and incorporate them into the library.

### PR DESCRIPTION
**Pull request by gmlewis**
Fixes #578.

### CODE REVIEW

File: github/with_appengine.go [hunk 1]
```diff
@@ -17,10 +17,8 @@ package github
 import (
 	"context"
 	"net/http"
-
-	"google.golang.org/appengine"
 )
 
 func withContext(ctx context.Context, req *http.Request) (context.Context, *http.Request) {
-	return appengine.WithContext(ctx, req), req
+	return ctx, req
```
Comment (shurcooL) [inline github/with_appengine.go]: Given this change, I think you can simplify `withContext` signature to return only `*http.Request` then. Can you?

Comment (shurcooL) [inline github/with_appengine.go]: Also, now that this func is a no-op for `appengine` case, I think you should add a comment explaining that. E.g.:

```Go
// No-op because appengine doesn't support adding context to a request.
return req
```

File: example/appengine/app.go [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+		http.NotFound(w, r)
+		return
+	}
+
+	ctx := appengine.NewContext(r)
+	ts := oauth2.StaticTokenSource(
+		&oauth2.Token{AccessToken: os.Getenv("GITHUB_AUTH_TOKEN")},
+	)
+	tc := oauth2.NewClient(ctx, ts)
+	client := github.NewClient(tc)
```
Comment (shurcooL) [inline example/appengine/app.go]: So a new client must be made for every incoming request? That seems pretty unfortunate.

File: example/appengine/app.go [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+
+	commits, _, err := client.Repositories.ListCommits(ctx, "google", "go-github", nil)
+	if err != nil {
+		log.Errorf(ctx, "ListCommits: %v", err)
+		return
```
Comment (shurcooL) [inline example/appengine/app.go]: You haven't written anything to `w` yet, so you could also do `http.Error(w, err.Error(), http.Status...)` here.

File: github/github.go [hunk 4]
```diff
@@ -399,7 +399,7 @@ func parseRate(r *http.Response) Rate {
 // The provided ctx must be non-nil. If it is canceled or times out,
 // ctx.Err() will be returned.
 func (c *Client) Do(ctx context.Context, req *http.Request, v interface{}) (*Response, error) {
-	ctx, req = withContext(ctx, req)
+	req = withContext(ctx, req)
```
Comment (shurcooL) [inline github/github.go]: This is one of those rare times where I feel it might be worth breaking the "context is always the first parameter" pattern.

Here, `withContext` is basically a method-as-a-function that adds `ctx` to `req`. I think seeing it like this:

```Go
req = withContext(req, ctx)
```

Might read better...

Well, after writing it up and looking at it for a few minutes, I'm not so sure it looks better. It seems about about the same. 😑

File: example/appengine/app.go (hunk 2 above)
Comment (gmlewis) [inline example/appengine/app.go]: This was expedient for this demo, but I believe it is possible to make a single client as a package global during initialization.

One caveat is that you can't call `os.Getenv` on App Engine within an `init` function due to the environment not being fully passed-in on app startup. The details are quite hairy.

So in cases like that, you could have a `sync.Once` block get the environment variable value and create the client before its first use... but I wanted to have a simple example here and not complicate things too much.

File: github/github.go (hunk 4 above)
Comment (gmlewis) [inline github/github.go]: Agreed.  I'll leave it alone.

**Comment by gmlewis** [comment]
Thank you, @shurcooL! Merging.
