### PR TITLE
Add secondary rate limit handling (prevent remote requests) and fix primary rate limit categories

### LINKED ISSUE #2633: Rate limit does not cover all categories & secondary rate limit not preventing requests
Hey,
First, thanks for all the great work on this client!

I noticed a couple of issues with the rate limits (please let me know if you think I should split it into two issues):

1. PR #2340 added support for all rate limit categories.
as @gmlewis pointed out in [this discussion](https://github.com/google/go-github/pull/2340/files/86f3ae6469d68ed74cb24551d9b26efe0eb12aa2#r857191632), all categories should be handled in the `catgory()` function.
The current code is:
```
func category(path string) rateLimitCategory {
	switch {
	default:
		return coreCategory
	case strings.HasPrefix(path, "/search/"):
		return searchCategory
	}
}
```
which is used in:
`rateLimitCategory := category(req.URL.Path)`
this variable is used in 2 points:
`c.checkRateLimitBeforeDo(req, rateLimitCategory)`
and
`c.rateLimits[rateLimitCategory] = response.Rate`

Now, since all categories (but search) are aggregated into the Core category on every request,
the result is that `checkRateLimitBeforeDo` might prevent the user from issuing a request, although the rate limit wasn't reached.
I can try to add partial support for that, at least for the fields that are in the documentation or are easy to deduce (e.g. code_scan_upload / integration_manifest)

2. The secondary rate limit is handled in `CheckResponse()`, but not in `checkRateLimitBeforeDo()`. 
As a result, there is no built-in protection against the secondary rate limit, which would be valuable.
I can try to add support for that as well, but I'm not sure to which request the secondary rate limit applies:
- The very same request
- All requests in the same category.
- Any request from that user.

I hope someone here might know the answer.

On the same note, I'd be glad to hear your thoughts on implementing an optional 'wait for secondary rate limit' configuration in the client. IMO the use case of waiting for the secondary rate limit is much more common than waiting for the hour-long rate limit (which also isn't supported).

### PR DESCRIPTION
**Pull request by gal-legit**
* Add check-before-do for secondary rate limit
* Add optional hook for secondary limits
* Add missing categories for primary rate limits

Notes:
- As far as I could see, there is no documented API for runner registration - so I didn't handle this case.

fixes #2633 

Edit:
Following the conversation in this PR, the actual changes are:
* Add check-before-do for secondary rate limit
* Add missing categories for primary rate limits
* Add examples for using [go-github-ratelimit](https://github.com/gofri/go-github-ratelimit)

### CODE REVIEW

**Comment by gal-legit** [comment]
I have just realized that the hook must get the client as a parameter (and it's reflected in the tests, where I use the wrong client for the retry). I'll push a fix for that

**Comment by gmlewis** [comment]
Hmmm... I'm not sure I'm happy about these changes, and I've got a heavy workload right now. Please give me a week to mull this over.

File: github/github.go [hunk 1]
```diff
@@ -1192,12 +1267,35 @@ const (
 )
 
 // category returns the rate limit category of the endpoint, determined by Request.URL.Path.
-func category(path string) rateLimitCategory {
+func category(method string, path string) rateLimitCategory {
```
Comment (gmlewis) [inline github/github.go:1270]: Please update comment on line 1269: "determined by HTTP method and Request.URL.Path."

Also, please remove the extra "string":

```go
func category(method, path string) rateLimitCategory {
```

File: github/github.go [hunk 2]
```diff
@@ -1192,12 +1267,35 @@ const (
...
+
+	// https://docs.github.com/en/rest/code-scanning#upload-an-analysis-as-sarif-data
+	case strings.HasSuffix(path, "/code-scanning/sarifs"):
+		return codeScanningUploadCategory
+
+	// https://docs.github.com/en/enterprise-cloud@latest/rest/scim
+	case strings.HasPrefix(path, "/scim/"):
+		return scimCategory
+
+		// missing a case for actionsRunnerRegistrationCategory: no API found
```
Comment (gmlewis) [inline github/github.go:1298]: This indentation seems off - did you run "gofmt" on this file?

File: github/github.go [hunk 3]
```diff
@@ -301,18 +303,31 @@ func addOptions(s string, opts interface{}) (string, error) {
 	return u.String(), nil
 }
 
+type clientOption func(*Client)
```
Comment (gmlewis) [inline github/github.go:306]:
```suggestion
type ClientOption func(*Client)
```

File: github/github.go [hunk 4]
```diff
@@ -301,18 +303,31 @@ func addOptions(s string, opts interface{}) (string, error) {
...
+type secondaryRateLimitHook func(ctx context.Context, client *Client, req *http.Request, orgError *AbuseRateLimitError) (*Response, error)
```
Comment (gmlewis) [inline github/github.go:307]:
```suggestion
type SecondaryRateLimitHook func(ctx context.Context, client *Client, req *http.Request, orgError *AbuseRateLimitError) (*Response, error)
```

File: github/github.go [hunk 5]
```diff
@@ -301,18 +303,31 @@ func addOptions(s string, opts interface{}) (string, error) {
...
+
+func WithSecondaryRateLimitHook(hook secondaryRateLimitHook) clientOption {
```
Comment (gmlewis) [inline github/github.go:309]: Please add GoDoc-style comments (complete sentences ending in punctuation) to the 3 new exported items on lines 306, 307, and 309.

**Review by gmlewis — CHANGES_REQUESTED** [review]
Thank you, @gal-legit .
I think this will be beneficial, but was initially unhappy with the added complexity in BareDo.
Let's move forward with the PR, and I apologize for the delay.

Please see if you can handle the currently-uncovered code path with a unit test if possible, and thank you for the very comprehensive tests you have already added!

**Comment by gal-legit** [comment]
hey @gal-legit, thanks for the feedback!

I feel you - this PR adds complexity and new behavior to the client, and I don't feel too comfortable with adding this "mess" to the very elegant and clean style of the client.

I think that we can actually benefit from the delay.
During this week, I tackled this issue for the project I'm working on.
It started as a meantime solution, but I now think that taking this approach is probably better,
and it allows us to drop the hook and let the users handle it (somewhat like caching/token).

Check out secondaryRateLimitWaiter [here](https://github.com/Legit-Labs/legitify/blob/0c8137910869332ad32151026aa1834e6b56728a/internal/clients/github/transport/secnodary_rate_limit.go).
If you like the idea of dropping it, I can remove all hook-related stuff from this PR.
Also, if you think that this reference is worth recommending (like the cache/etc.), I can move that secondary rate limit transport to a different repo so that everyone can use it as a plugin.
Obviously, I'll also adjust it to fit general availability (remove the injecter and the log, add support for max-sleep, etc.).

Let me know what you think, and I'll continue from there.
Thanks!

**Comment by gmlewis** [comment]
> Let me know what you think, and I'll continue from there.

Ah, genius!  I think handling it in an external-to-this-repo RoundTripper is a thing of beauty!
Let's proceed that way, and then this PR could instead point to the external RoundTripper in its examples and/or comments.

Thank you, @gal-legit !

**Comment by gal-legit** [comment]
@gmlewis cool! I'll do the separation and update the PR with all the fixes and reference when it's ready.
I should keep the basic handling of the secondary rate limit in the client though. right?
i.e., saving it in the response and handling it in `checkSecondaryRateLimitBeforeDo()` to prevent remote requests, but with an implementation that looks just like `checkRateLimitBeforeDo()` so it isn't messy.

**Comment by gmlewis** [comment]
Hmmm... would that tie this "go-github" repo to the external RoundTripper repo?
Is there a way to add the functionality without adding an external dependency?

**Comment by gal-legit** [comment]
1. I meant in the context of the PR -- adding the handling to improve the client, regardless of the RoundTripper.
2. The current implementation of the RoundTripper uses go-github because the hosting project already does (so I didn't mind). The standalone version would parse the header and remove the dependency on go-github. So it shouldn't be tied anyway.

**Comment by gmlewis** [comment]
OK, cool... I think I understand, but it will become more clear as I see the PR update.
Thanks again, @gal-legit !  I appreciate your patience and willingness to make this improvement!

**Comment by gal-legit** [comment]
I have the new repo ready (https://github.com/gofri/go-github-ratelimit),
gonna have the changes to the PR ready soon

**Comment by gmlewis** [comment]
> I have the new repo ready (https://github.com/gofri/go-github-ratelimit), gonna have the changes to the PR ready soon

Woohoo!  I gave it its very first GitHub star!  :smile:

File: github/github.go (hunk 2 above)
Comment (gal-legit) [reply github/github.go]: yep, this is using gofmt.
I guess that it associates the comment with the case so it requires extra indentation.
I rearranged the comment to be part of the "default" case, so it makes more sense and there's no weird indentation.

**Comment by gal-legit** [comment]
@gmlewis
I pushed the new version.
I resolved the comments that are related to the hooks because it's now omitted. Also, I responded to (and applied) the fixes from the other comments.

File: example/ratelimit/main.go [hunk 6]
```diff
@@ -0,0 +1,39 @@
+// Copyright 2017 The go-github AUTHORS. All rights reserved.
```
Comment (gmlewis) [inline example/ratelimit/main.go:1]:
```suggestion
// Copyright 2023 The go-github AUTHORS. All rights reserved.
```

File: github/github.go (hunk 1 above)
Comment (gmlewis) [reply github/github.go:1245]: It looks like you still need to remove the extra "string". Please see my last comment above.

**Review by gmlewis — CHANGES_REQUESTED** [review]
Thank you, @gal-legit !

**Comment by gal-legit** [comment]
@gmlewis oops, done

**Comment by gmlewis** [comment]
We keep getting linter errors.

```
level=error msg="Running error: 1 error occurred:\n\t* can't run linter goanalysis_metalinter: inspect: failed to load package : could not load export data: no export data for \"github.com/gofri/go-github-ratelimit/github_ratelimit\"\n\n"
```

It looks like you need to make a versioned release (0.0.1 maybe?) of your new external package, then update this PR to explicitly pull in that version in the `examples/go.mod` file to clear up this problem.

**Comment by gmlewis** [comment]
It looks like there is a problem on Windows... I think it may have to do with how time comparisons are performed in your test.

```
    github_test.go:1461: abuseRateLimitErr RetryAfter = 2m3s, want 2m3s
--- FAIL: TestDo_rateLimit_abuseRateLimitError_retryAfter (0.00s)
```

Please check out [time.Equal](https://pkg.go.dev/time#Time.Equal) and see if you can fix this.

**Comment by gal-legit** [comment]
@gmlewis 
My bad. It was actually a bug in the test:
I meant to test the delta between the expected and actual retry-after is less than a second,
but, I forgot to multiply by time.Second and the comparison was the other way around.
So it actually tested that the delta is bigger than a nanosecond. I guess that the timer has a lower resolution on Win so it caught it.
p.s. it's comparing time.Duration, so AFAIK it should be fine as long as I compare it to time.Second.

**Comment by gmlewis** [comment]
> My bad. It was actually a bug in the test:

I find it bizarre that only the Windows version of the test caught the issue, and not the Linux build!?!?!?

OK, thanks.  I have to step out but hopefully will get back to this PR later tonight.

**Comment by gofri** [comment]
LOL, I found it a bit embarrassing for me, being a Linux kernel engineer.
I guess that sometimes having a worse implementation might be good for testing 🤷

**Comment by gmlewis** [comment]
> being a Linux kernel engineer.

Cool! I'd love to ask you about your favorite distros, but this is probably not the right forum. 😂

File: github/github_test.go [hunk 7]
```diff
@@ -1136,6 +1141,36 @@ func TestDo_rateLimit(t *testing.T) {
 	}
 }
 
+func TestDo_rateLimitCategory(t *testing.T) {
+	if c := category(http.MethodGet, "/"); c != coreCategory {
```
Comment (gmlewis) [inline github/github_test.go:1145]: In reason that this is not a table-driven test?

I'm OK leaving it as-is if you want... since it would probably be the same number of lines, but I often find that table-driven tests are easier to read because you can just look at the data all in one place.

But no biggie... I'm fine either way.

File: github/github_test.go [hunk 8]
```diff
@@ -1407,6 +1442,27 @@ func TestDo_rateLimit_abuseRateLimitError_retryAfter(t *testing.T) {
 	if got, want := *abuseRateLimitErr.RetryAfter, 123*time.Second; got != want {
 		t.Errorf("abuseRateLimitErr RetryAfter = %v, want %v", got, want)
 	}
+
+	// expect prevention of a following request
+	_, err = client.Do(ctx, req, nil)
+
+	if err == nil {
```
Comment (gmlewis) [inline github/github_test.go:1449]:
```suggestion
	if _, err := client.Do(ctx, req, nil); err == nil {
```

**Review by gmlewis — CHANGES_REQUESTED** [review]
Thank you, @gal-legit !
One minor tweak please, plus one question, otherwise LGTM.

After the tweak, we should be ready for an LGTM+Approval from any other contributor to the repo before merging.

File: github/github_test.go (hunk 7 above)
Comment (gal-legit) [reply github/github_test.go]: tbh I just tried to follow TestRateLimits & TestRateLimits_overQuota,
but I fixed it to be table-driven (and fixed those two while at it)

File: github/github_test.go (hunk 8 above)
Comment (gal-legit) [reply github/github_test.go]: I thought it'd be a bit misleading to put it inside the if statement because we use err later (casting to *AbuseRateLimitError), but I fixed it anyway

File: github/github_test.go [hunk 9]
```diff
@@ -1136,6 +1141,67 @@ func TestDo_rateLimit(t *testing.T) {
...
 }
 
+func TestDo_rateLimitCategory(t *testing.T) {
+	tests := []struct {
+		method   string
+		url      string
+		category rateLimitCategory
+	}{
+		{
+			http.MethodGet,
```
Comment (gmlewis) [inline github/github_test.go:1151]: This is a tiny nit, and if you don't want to do this, I'm fine...
but in this repo we prefer to label the fields for clarity-at-a-quick-glance (e.g. `method: http.MethodGet,`, etc.).
I'm going to go ahead and approve, but if you want to update, great.

**Review by gmlewis — APPROVED** [review]
Thank you, @gal-legit !

File: github/github_test.go (hunk 9 above)
Comment (gal-legit) [reply github/github_test.go:1151]: sure, np, I'll do that. 
p.s. Ubuntu for desktop, RHEL/fedora-based for server 🙃

**Review by valbeat — APPROVED** [review]
LGTM!

**Comment by gmlewis** [comment]
Thank you, @valbeat !
Merging.
