### PR TITLE
do not encode / in ref names

### LINKED ISSUE #1432: Refs should not encode /
The commit #1099 changed the ref name to be URL Query encoded. This breaks ref names which contain a /:

A call to `curl -vH "Authorization: Bearer $TOKEN" https://$GHE_URL/repos/o/r/git/ref/heads/master` works, but `https://$GHE_URL/repos/o/r/git/ref/heads%2Fmaster` (like `GetRef()`, `GetRefs()` use it) fail with 404.

### PR DESCRIPTION
**Pull request by vetinari**
fixes #1432

Signed-off-by: Hanno Hecker <hanno@zalando.de>

### CODE REVIEW

File: github/git_refs.go [hunk 1]
```diff
@@ -79,10 +79,12 @@ func (s *GitService) GetRef(ctx context.Context, owner string, repo string, ref
 	return r, resp, nil
 }
 
+// refURLEscape escapes every path segment of the given ref. Those must
+// not contain escaped "/" - as "%2F" - or github will not recognize it.
 func refURLEscape(ref string) string {
 	parts := strings.Split(ref, "/")
 	for i, s := range parts {
-		parts[i] = url.QueryEscape(s)
+		parts[i] = url.PathEscape(s)
```
Comment (gmlewis) [inline github/git_refs.go]: Hmmm... with this change from `url.QueryEscape` to `url.PathEscape`, I'm now concerned that we are breaking what was fixed in #1099.

Can you please add a unit test that demonstrates the URL found in #1099?

Unfortunately, I did not request that unit tests be added in #1099 to demonstrate the before/after changes. :-(
But I'm trying to fix that now.

Comment (vetinari) [reply github/git_refs.go]: There's one in #1118 (issue #1101). This still works, `GetCommitSHA1()` got the `refURLEscape()` also. I've added a test case for the original trailing `%` as given in #1099 where http.NewRequest was failing to parse the URL.

**Comment by gmlewis** [comment]
Thank you, @wesleimp!
Merging.
